fix: GSuite sync and config helper script bug fix (#2063)
### Summary
Encountered some errors when I was trying to run GSuite Sync with OAuth.
Made very minor changes.

Additional References :

1. Actual scope for retrieving users is
https://www.googleapis.com/auth/admin.directory.user.readonly (was
missing a dot after user earlier). Causes the helper script to otherwise
run into a authorizationBlocked screen for invalid scope. **Ref:**
https://developers.google.com/identity/protocols/oauth2/scopes

2. create_scoped line was causing the gsuite sync to crash. Ig this is
something aimed for service accounts, with OAuth all scopes should be
decided and fixed at the time of getting the respective access token
with the req scopes. I couldn't find much documentation on create_scoped
as its deprecated. Either way, it ran well and good without this line.
**Ref:**
https://googleapis.dev/python/google-auth/1.20.1/reference/google.auth.credentials.html
**Ref:** https://datatracker.ietf.org/doc/html/rfc6749 (section 1.4 and
1.5 are helpful).

### Checklist

Provide proof that this works (this makes reviews move faster). Please
perform one or more of the following:
- [ ] Update/add unit or integration tests.
- [ ] Include a screenshot showing what the graph looked like before and
after your changes.
- [x] Include console log trace showing what happened before and after
your changes.


**Before**
```
INFO:cartography.sync:Starting sync with update tag '1763470318'
INFO:cartography.sync:Starting sync stage 'gsuite'
INFO:cartography.intel.gsuite:Attempting to authenticate to GSuite using OAuth
ERROR:cartography.sync:Unhandled exception during sync stage 'gsuite'
Traceback (most recent call last):
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/sync.py", line 150, in run
    stage_func(neo4j_session, config)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/util.py", line 225, in timed
    return method(*args, **kwargs)
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/intel/gsuite/__init__.py", line 123, in start_gsuite_ingestion
    creds = creds.create_scoped(OAUTH_SCOPES)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Credentials' object has no attribute 'create_scoped'. Did you mean: 'granted_scopes'?
Traceback (most recent call last):
  File "/home/Flarebound/.local/bin/cartography", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/cli.py", line 1385, in main
    sys.exit(CLI(prog="cartography").main(argv))
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/cli.py", line 1360, in main
    return cartography.sync.run_with_config(self.sync, config)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/sync.py", line 290, in run_with_config
    return sync.run(neo4j_driver, config)
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/sync.py", line 150, in run
    stage_func(neo4j_session, config)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/util.py", line 225, in timed
    return method(*args, **kwargs)
  File "/home/Flarebound/CNCF/cartography-personal/cartography/cartography/intel/gsuite/__init__.py", line 123, in start_gsuite_ingestion
    creds = creds.create_scoped(OAUTH_SCOPES)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Credentials' object has no attribute 'create_scoped'. Did you mean: 'granted_scopes'?
```

**After**
```
INFO:cartography.sync:Starting sync with update tag '1763470368'
INFO:cartography.sync:Starting sync stage 'gsuite'
INFO:cartography.intel.gsuite:Attempting to authenticate to GSuite using OAuth
INFO:cartography.intel.gsuite.users:Ingesting 1 gsuite tenants
INFO:cartography.intel.gsuite.users:Ingesting 1 gsuite users for customer C042gn4cy
INFO:cartography.graph.statement:Completed GSuiteUser statement #1
INFO:cartography.graph.statement:Completed GSuiteUser statement #2
INFO:cartography.graph.job:Finished job GSuiteUser
INFO:cartography.intel.gsuite.groups:Ingesting 4 gsuite groups
INFO:cartography.intel.gsuite.groups:Ingesting 0 group member relationships
INFO:cartography.intel.gsuite.groups:Ingesting 0 group owner relationships
INFO:cartography.graph.statement:Completed GSuiteGroup statement #1
INFO:cartography.graph.statement:Completed GSuiteGroup statement #2
INFO:cartography.graph.statement:Completed GSuiteGroup statement #3
INFO:cartography.graph.statement:Completed GSuiteGroup statement #4
INFO:cartography.graph.job:Finished job GSuiteGroup
INFO:cartography.graph.statement:Completed MEMBER_GSUITE_GROUP statement #1
INFO:cartography.graph.job:Finished job MEMBER_GSUITE_GROUP
INFO:cartography.graph.statement:Completed OWNER_GSUITE_GROUP statement #1
INFO:cartography.graph.job:Finished job OWNER_GSUITE_GROUP
INFO:cartography.sync:Finishing sync stage 'gsuite'
```

If you are changing a node or relationship:
- [x] Update the
[schema](https://github.com/cartography-cncf/cartography/tree/master/docs/root/modules)
and
[readme](https://github.com/cartography-cncf/cartography/blob/master/docs/schema/README.md).

If you are implementing a new intel module:
- [ ] Use the NodeSchema [data
model](https://cartography-cncf.github.io/cartography/dev/writing-intel-modules.html#defining-a-node).

- [x] Confirm that the linter actually passes (submitting a PR where the
linter fails shows reviewers that you did not test your code and will
delay your review).

Signed-off-by: Daksh Rathore <daksh.rathore9@gmail.com>
Co-authored-by: Jeremy Chapeau <113923302+jychp@users.noreply.github.com>