fix(ecr): ECR image layers batching (#2005)
### Summary
Make batch_size configurable in `load`, `load_graph_data`, and
`load_matchlinks` for modules with larger amounts of data that could
exceed Neo4j's transaction memory limits. Adjust ECR image layers to be
1000 instead of 10000 due to this error in an environment with 100k
images.

```
neo4j.exceptions.TransientError: {code: Neo.TransientError.General.MemoryPoolOutOfMemoryError} {message: The allocation of an extra 663.2 MiB would use more than the limit 824.0 MiB. Currently using 731.5 MiB. dbms.memory.transaction.total.max threshold reached}
```

### Checklist

Provide proof that this works (this makes reviews move faster). Please
perform one or more of the following:
~~- [ ] Update/add unit or integration tests.~~ intentionally didn't
change tests to show that this shows
~~- [ ] Include a screenshot showing what the graph looked like before
and after your changes.~~ intentionally looks the same
~~- [ ] Include console log trace showing what happened before and after
your changes.~~ not required - tests capture

If you are changing a node or relationship:
- [x] Update the
[schema](https://github.com/cartography-cncf/cartography/tree/master/docs/root/modules)
and
[readme](https://github.com/cartography-cncf/cartography/blob/master/docs/schema/README.md).

If you are implementing a new intel module:
- [x] Use the NodeSchema [data
model](https://cartography-cncf.github.io/cartography/dev/writing-intel-modules.html#defining-a-node).
- [x] Confirm that the linter actually passes (submitting a PR where the
linter fails shows reviewers that you did not test your code and will
delay your review).

---------

Signed-off-by: Kunaal Sikka <kunaal@subimage.io>